const url = 'localhost://3000'

const app = new Vue({
    el:'#app',
    id:'',
    creator:'',
    path:'',
    data:[],
    method:{
        videoUpload:function(){
            Axios
                .post(`${url}/videoupload`,{
                    creator:this.creator,
                    path:this.path
                })
                .then(data=>{
                    console.log(data)
                })
                .catch(err=>{
                    console.log(err)
                })
        },
        videoList:function(){
            Axios
                .get(`${url}/videolist`)
                .then(data=>{
                    console.log(data)
                })
                .catch(err=>{
                    console.log(err)
                })
        },
        videoDownload:function(){
            Axios
                .get(`${url}/videodownload`)
                .then(data=>{
                    console.log(data)
                })
                .catch(err=>{
                    console.log(err)
                })
        }
    }
})